apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: only-view-cluster
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: [get, list, watch]  
  
  - apiGroups: [""]
    resources: ["pods"]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deploy_view

subjects:
- kind: User
  name: deploy_view
  apiGroup: rbac.authorization.k8s.io

roleRef:
  kind: ClusterRole
  name: only-view-cluster
  apiGroup: rbac.authorization.k8s.io
