apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: only-view-prod
  namespace: prod
rules:
  - apiGroups: ["apps"]
    resources: ["*"]
    verbs: [get, list, watch]  
  
  - apiGroups: [""]
    resources: ["*"]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
   name: prod_view
   namespace: prod
subjects:
- kind: User
  name: prod_view
  apiGroup: rbac.authorization.k8s.io

roleRef:
  kind: Role
  name: only-view-prod
  apiGroup: rbac.authorization.k8s.io
