apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-namespace-admin
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: sa-namespace-admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
subjects:
- kind: ServiceAccount
  name: sa-namespace-admin
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
