apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-home
  labels:
    app: nfs-pv-app
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem  
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /backups 
    server: 10.88.25.83
