kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs
spec:
  volumeMode: Filesystem
  accessModes: 
    - ReadWriteMany
  storageClassName: ""    
  resources:
    requests:
      storage: 10Gi
  volumeName: nfs-pv-home 
  selector: 
    matchLabels: 
      app: nfs-pv-app     
