apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: natig
  namespace: default

subjects:
- kind: ServiceAccount
  name: natig
  namespace: default

roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
