apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: list-deployment-rafael
  namespace: default
rules:
  - apiGroups: ["apps"]
    resources: [ "deployments" ] 
    verbs: [ get, list, update ]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: [ get, list ]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: [get, list]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rafael
  namespace: default

subjects:
- kind: ServiceAccount
  name: rafael
  namespace: default

roleRef:
  kind: Role
  name: list-deployment-rafael
  apiGroup: rbac.authorization.k8s.io

